title: randomOps
subtitle: Podcast, Community and Preman Infra

baseurl: ""

markdown: kramdown

tracking_id: #

footer_url: "http://randomops.com"
footer_text: "RandomOps | 2018"

profile-picture: randomops.jpg

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
